# -*- coding: utf-8 -*-
"""Decision Tree_Hernando Te_9°B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KLAGoWWk82ZIr2fWrczSOzq-SIeT0nz8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn. preprocessing import LabelEncoder
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier,plot_tree

#All the necesary libreries to  reda the datseet, plot tables´and in this case use the algortim decision tree.

df=pd.read_csv('/content/kaggle.csv')

df.head(100)

valores_Nan = df.isna().sum()
print(valores_Nan[valores_Nan > 0])

#With this part of the code was trying to find the rows without data of all the dataseet

import pandas as pd
for columna in df.columns:
    conteo_variables = df[columna].value_counts()
    variables_repetidas = conteo_variables[conteo_variables > 1]
    if not variables_repetidas.empty:
        print(f"\nColumna: {columna}")
        print(variables_repetidas)

        #In this part of the code the previos lines were  used to identify and display variables that have duplicates in each column of the DataFrame.

columnas_a_quitar = ['Ref Pubyr', 'Cc','Formation']
df = df.drop(columnas_a_quitar, axis=1, errors='ignore')
#This code will remove the 'Ref Pubyr', 'Cc' and 'Formation' columns from the DataFrame df,
 # and if any of these columns do not exist in the DataFrame, it will not raise an error.

df.head()

from sklearn.preprocessing import LabelEncoder
cols_to_encode = ['What Dinosaurs Eat', 'State','Accepted Name', 'Country', 'Diet', 'Early Interval', 'Geological Interval', 'Geological Time Period','Ref Author']
le = LabelEncoder()
for columna in cols_to_encode:
    df[columna] = le.fit_transform(df[columna])

#With the librerie sklearn that used the class 'LabelEncoder'
# to transform  the categoric columns to numeric values.

df

df = df.sort_values(by=df.columns.tolist())
X = df.drop(columns=['Country'])
y = df['Country']
df = pd.concat([X, y], axis=1)

#Division of the dataset in X and Y where the Y is our target 'Country'

df.head(50)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
modelo_arbol = DecisionTreeClassifier(random_state=42)
modelo_arbol.fit(X_train, y_train)
predicciones_numericas = modelo_arbol.predict(X_test)
le_diet = LabelEncoder()
y_test_numericas = le_diet.fit_transform(y_test)

precision = accuracy_score(y_test_numericas, predicciones_numericas)
print(f'Precisión del modelo: {precision}')
etiquetas_originales_str = list(map(str, le_diet.classes_))


#Division of the data to train and test the model , in which at the end show the accuracy of the model.

plt.figure(figsize=(16, 13))
plot_tree(modelo_arbol, filled=True, feature_names=X.columns, class_names=etiquetas_originales_str)
plt.savefig("arbol_decision.pdf", format="pdf")
plt.show()

!jupyter nbconvert --execute  --to html "/content/Decision_Tree_Hernando_Te_9°B (1).ipynb"